version: '3.1'

services:
  my_api:
    build:
      context: .
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    volumes:
      - "./:/app"
    ports:
      - 3000:3000
    command:
      - /bin/sh
      - -c
      - |
        rails db:setup db:migrate
        rails db:seed
        bundle exec rails s -p 3000 -b 0.0.0.0
